alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: my-go-database
  engine: PG
  name: my-go-database
  version: "17"
  production: true
envs:
- key: POSTGRES_HOSTNAME
  scope: RUN_AND_BUILD_TIME
  value: ${my-go-database.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${my-go-database.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${my-go-database.PASSWORD}
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${my-go-database.DATABASE}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${my-go-database.PORT}
- key: POSTGRES_TIMEZONE
  scope: RUN_AND_BUILD_TIME
  value: Europe/Stockholm
- key: POSTGRES_SSLMODE
  scope: RUN_AND_BUILD_TIME
  value: prefer
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: heman-my-go-project
    match:
      path:
        prefix: /
  - component:
      name: dpage-pgadmin-4
    match:
      path:
        prefix: /dpage-pgadmin-4
name: clownfish-app
region: ams
services:
- http_port: 8080
  image:
    registry: heman
    registry_type: GHCR
    repository: my-go-project
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: heman-my-go-project
- envs:
  - key: PGADMIN_DEFAULT_PASSWORD
    scope: RUN_TIME
    value: 1Hemligt!
  - key: PGADMIN_DEFAULT_EMAIL
    scope: RUN_TIME
    value: jimmy.hedman@gmail.com
  - key: SCRIPT_NAME
    scope: RUN_TIME
    value: /dpage-pgadmin-4
  http_port: 8080
  image:
    registry: dpage
    registry_type: DOCKER_HUB
    repository: pgadmin4
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: dpage-pgadmin-4